Bumped dependency versions and improved build.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,7 +27,7 @@ jobs:
                 name: Install build dependencies
                 run: |
                     python -m pip install --upgrade pip
-                    pip install poetry tox
+                    pip install poetry tox pre-commit
             -
                 name: Test with tox
                 run: |
@@ -36,3 +36,8 @@ jobs:
                 name: Build the Docker image
                 run: |
                     docker build .
+            -
+                name: Run coveralls
+                # the || true is because coveralls returns a nonzero exit code on warnings, etc.
+                run: |
+                    coveralls || true
